# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      
    - name: Restore Nuget Package
    - uses: warrenbuckley/Setup-Nuget@v1
    - run: nuget restore .\Chat-Chan.sln
    
    - name: Build
    - uses: warrenbuckley/Setup-MSBuild@v1 
    - run: msbuild .\Chat-Chan.sln -p:Configuration=Release
